# Generated by Django 5.0.6 on 2024-06-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recipe_cook_time_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
    ]
